services:
  iptv-checker:
    image: registry.cn-hongkong.aliyuncs.com/cgg888/iptv-web-checker:1.0.0
    container_name: iptv-checker
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge
