version: '3'

services:
  iptv-checker:
    image: ghcr.io/cgg888/iptv-web-checker:1.0.0
    container_name: iptv-checker
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
